

#
#spring.datasource.url=jdbc:mysql://localhost:3306/mailcasting?useSSL=false&createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#hibernate.show_sql = true
#hibernate.format_sql = true
#hibernate.hbm2ddl.auto = update
#spring.jpa.generate-ddl=true

server.port : 8081

spring:
  resources.add-mappings: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:mariadb://localhost:3306/mailcasting?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
